name:                engrave
version:             0.1.0.0
github:              "matthunz/engrave"
license:             MPL-2.0
license-file:        LICENSE
author:              Matt Hunzinger
maintainer:          matthunz2@gmail.com
copyright:           2024 Matt Hunzinger

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matthunz/engrave#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- containers
- file-embed
- tree-sitter
- tree-sitter-haskell
- conduit
- conduit-extra
- json-rpc
- aeson
- text
- monad-logger

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  engrave-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - engrave

tests:
  engrave-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - engrave
