resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/29.yaml

packages:
- .

extra-deps:
  - git: https://github.com/matthunz/haskell-tree-sitter.git
    commit: b2b32e22701622db5096ec147512c82e66ce7ab4
    subdirs:
      - tree-sitter
      - tree-sitter-haskell
